/**
 * AuthGuardian AI — Markdown Report Generator
 * ==============================================
 * Generates enterprise-grade markdown reports for deployment review,
 * code review, and combined summaries.
 *
 * @module markdown-generator
 */

const config = require('../../configs/review-config');
const { getSeverityDistribution, getDeploymentReadiness, calculateComplianceScore, calculateSecureCodingScore } = require('../severity-engine');

/**
 * Generates the deployment review markdown report (deployment-review.md).
 *
 * @param {object} deploymentResult - Output from deployment-review engine
 * @param {object} summary - Output from severity-engine generateSummary
 * @returns {string} Markdown content
 */
function generateDeploymentReport(deploymentResult, summary) {
  const now = new Date().toISOString();
  const readiness = summary.readiness;
  const distribution = summary.distribution;

  let md = '';

  // ── Header
  md += `# 🛡️ AuthGuardian AI — Deployment Review Report\n\n`;
  md += `> **Generated:** ${now}  \n`;
  md += `> **Engine:** AuthGuardian AI v${config.meta.version}  \n`;
  md += `> **Mode:** Deployment Configuration Review  \n\n`;

  // ── Executive Summary
  md += `## 📋 Executive Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| **Deployment Readiness** | ${readiness.label} |\n`;
  md += `| **Risk Score** | ${summary.riskScore}/100 |\n`;
  md += `| **Compliance Score** | ${summary.compliance.score}/100 (${summary.compliance.grade}) |\n`;
  md += `| **Total Files Reviewed** | ${deploymentResult.stats.totalFiles} |\n`;
  md += `| **Total Findings** | ${deploymentResult.stats.totalFindings} |\n`;
  md += `| **Added Resources** | ${deploymentResult.stats.added} |\n`;
  md += `| **Modified Resources** | ${deploymentResult.stats.modified} |\n`;
  md += `| **Deleted Resources** | ${deploymentResult.stats.deleted} |\n\n`;

  md += `**Readiness Assessment:** ${readiness.reason}\n\n`;

  // ── Risk Breakdown
  md += `## 📊 Risk Breakdown\n\n`;
  md += `| Severity | Count | Status |\n`;
  md += `|----------|-------|--------|\n`;
  md += `| 🔴 CRITICAL | ${distribution.CRITICAL} | ${distribution.CRITICAL > 0 ? '⛔ Action Required' : '✅ Clear'} |\n`;
  md += `| 🟠 HIGH | ${distribution.HIGH} | ${distribution.HIGH > 0 ? '⚠️ Review Required' : '✅ Clear'} |\n`;
  md += `| 🟡 MEDIUM | ${distribution.MEDIUM} | ${distribution.MEDIUM > 0 ? '📋 Advisory' : '✅ Clear'} |\n`;
  md += `| 🔵 LOW | ${distribution.LOW} | ${distribution.LOW > 0 ? 'ℹ️ Informational' : '✅ Clear'} |\n\n`;

  // ── Files Reviewed
  md += `## 📁 Files Reviewed\n\n`;
  md += generateFilesTable(deploymentResult.reviewedFiles);

  // ── Security Findings
  if (deploymentResult.findings.length > 0) {
    md += `## 🔒 Security & IAM Findings\n\n`;
    md += generateFindingsSection(deploymentResult.findings);
  } else {
    md += `## 🔒 Security & IAM Findings\n\n`;
    md += `> ✅ No security or IAM findings detected. Configuration looks clean.\n\n`;
  }

  // ── Recommendations
  md += `## 💡 Recommendations\n\n`;
  md += generateRecommendationsSection(deploymentResult.findings);

  // ── Deployment Readiness Status
  md += `## 🚀 Deployment Readiness\n\n`;
  md += `| Status | Decision |\n`;
  md += `|--------|----------|\n`;
  md += `| ${readiness.label} | ${readiness.canDeploy ? '✅ Proceed with deployment' : '⛔ Address findings before deployment'} |\n\n`;
  md += `${readiness.reason}\n\n`;

  // ── Footer
  md += `---\n`;
  md += `*Report generated by AuthGuardian AI v${config.meta.version} — Toyota Motor North America IAM Platform Engineering*\n`;

  return md;
}

/**
 * Generates the code review markdown report (ai-review-report.md).
 *
 * @param {object} codeResult - Output from code-review engine
 * @param {object} summary - Output from severity-engine generateSummary
 * @returns {string} Markdown content
 */
function generateCodeReviewReport(codeResult, summary) {
  const now = new Date().toISOString();
  const distribution = getSeverityDistribution(codeResult.findings);

  let md = '';

  // ── Header
  md += `# 🔍 AuthGuardian AI — Secure Code Review Report\n\n`;
  md += `> **Generated:** ${now}  \n`;
  md += `> **Engine:** AuthGuardian AI v${config.meta.version}  \n`;
  md += `> **Mode:** Auth0 Secure Code Analysis  \n\n`;

  // ── Executive Summary
  md += `## 📋 Executive Summary\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| **Secure Coding Score** | ${summary.secureCoding.score}/100 (${summary.secureCoding.grade}) |\n`;
  md += `| **Code Files Reviewed** | ${codeResult.stats.totalCodeFiles} |\n`;
  md += `| **Total Findings** | ${codeResult.stats.totalFindings} |\n`;
  md += `| **CRITICAL** | ${distribution.CRITICAL} |\n`;
  md += `| **HIGH** | ${distribution.HIGH} |\n`;
  md += `| **MEDIUM** | ${distribution.MEDIUM} |\n`;
  md += `| **LOW** | ${distribution.LOW} |\n\n`;

  // ── Files Reviewed
  md += `## 📁 Code Files Reviewed\n\n`;
  if (codeResult.reviewedFiles.length > 0) {
    md += generateFilesTable(codeResult.reviewedFiles);
  } else {
    md += `> No Auth0 code files (Actions/Rules/Hooks) were changed in this deployment.\n\n`;
  }

  // ── Code Findings
  if (codeResult.findings.length > 0) {
    md += `## 🛡️ Secure Code Findings\n\n`;
    md += generateFindingsSection(codeResult.findings);
  } else {
    md += `## 🛡️ Secure Code Findings\n\n`;
    md += `> ✅ No code security findings detected. Code follows Auth0 best practices.\n\n`;
  }

  // ── Auth0 Best Practices Checklist
  md += `## ✅ Auth0 Best Practices Checklist\n\n`;
  md += generateBestPracticesChecklist(codeResult);

  // ── Recommendations
  md += `## 💡 Recommendations\n\n`;
  md += generateRecommendationsSection(codeResult.findings);

  // ── Footer
  md += `---\n`;
  md += `*Report generated by AuthGuardian AI v${config.meta.version} — Toyota Motor North America IAM Platform Engineering*\n`;

  return md;
}

/**
 * Generates a combined GitHub Actions job summary.
 *
 * @param {object} deploymentResult
 * @param {object} codeResult
 * @param {object} summary
 * @returns {string} Markdown for GITHUB_STEP_SUMMARY
 */
function generateJobSummary(deploymentResult, codeResult, summary) {
  const readiness = summary.readiness;

  let md = '';

  md += `## 🛡️ AuthGuardian AI — Review Summary\n\n`;
  md += `### ${readiness.label}\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Risk Score | **${summary.riskScore}/100** |\n`;
  md += `| Compliance Score | **${summary.compliance.score}/100** (${summary.compliance.grade}) |\n`;
  md += `| Secure Coding Score | **${summary.secureCoding.score}/100** (${summary.secureCoding.grade}) |\n`;
  md += `| Files Reviewed | ${deploymentResult.stats.totalFiles} config + ${codeResult.stats.totalCodeFiles} code |\n`;
  md += `| Total Findings | ${summary.totalFindings} |\n`;
  md += `| 🔴 CRITICAL | ${summary.distribution.CRITICAL} |\n`;
  md += `| 🟠 HIGH | ${summary.distribution.HIGH} |\n`;
  md += `| 🟡 MEDIUM | ${summary.distribution.MEDIUM} |\n`;
  md += `| 🔵 LOW | ${summary.distribution.LOW} |\n\n`;

  md += `${readiness.reason}\n\n`;

  // Show top findings (up to 10)
  const allFindings = [...(deploymentResult.findings || []), ...(codeResult.findings || [])];
  const topFindings = allFindings
    .sort((a, b) => severityOrder(a.severity) - severityOrder(b.severity))
    .slice(0, 10);

  if (topFindings.length > 0) {
    md += `### Top Findings\n\n`;
    for (const f of topFindings) {
      const icon = config.severity.levels[f.severity]?.color || '❓';
      md += `- ${icon} **${f.severity}** — ${f.title} (${f.file || 'cross-file'})\n`;
    }
    md += `\n`;
  }

  md += `> Full reports available as workflow artifacts: \`deployment-review.md\` and \`ai-review-report.md\`\n`;

  return md;
}

/**
 * Generates a PR comment body.
 *
 * @param {object} deploymentResult
 * @param {object} codeResult
 * @param {object} summary
 * @returns {string} Markdown for PR comment
 */
function generatePrComment(deploymentResult, codeResult, summary) {
  const readiness = summary.readiness;

  let md = '';

  md += `${config.github.commentHeader}\n`;
  md += `## 🛡️ AuthGuardian AI — Deployment Review\n\n`;
  md += `### ${readiness.label}\n\n`;

  // Summary table
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Risk Score | **${summary.riskScore}/100** |\n`;
  md += `| Compliance | **${summary.compliance.score}/100** (${summary.compliance.grade} — ${summary.compliance.label}) |\n`;
  md += `| Secure Coding | **${summary.secureCoding.score}/100** (${summary.secureCoding.grade} — ${summary.secureCoding.label}) |\n`;
  md += `| Config Files | ${deploymentResult.stats.totalFiles} (${deploymentResult.stats.added} added, ${deploymentResult.stats.modified} modified, ${deploymentResult.stats.deleted} deleted) |\n`;
  md += `| Code Files | ${codeResult.stats.totalCodeFiles} |\n`;
  md += `| Findings | ${summary.totalFindings} (🔴${summary.distribution.CRITICAL} 🟠${summary.distribution.HIGH} 🟡${summary.distribution.MEDIUM} 🔵${summary.distribution.LOW}) |\n\n`;

  // Show critical/high findings in full
  const criticalHigh = [...(deploymentResult.findings || []), ...(codeResult.findings || [])]
    .filter(f => f.severity === 'CRITICAL' || f.severity === 'HIGH')
    .sort((a, b) => severityOrder(a.severity) - severityOrder(b.severity));

  if (criticalHigh.length > 0) {
    md += `### ⚠️ Critical & High Findings\n\n`;
    for (const f of criticalHigh.slice(0, 15)) {
      const icon = config.severity.levels[f.severity]?.color || '❓';
      md += `<details>\n<summary>${icon} <strong>${f.severity}</strong> — ${f.title}</summary>\n\n`;
      md += `**File:** \`${f.file || 'N/A'}\`  \n`;
      md += `**Category:** ${f.category}  \n\n`;
      md += `**Impact:**  \n${f.impact}\n\n`;
      md += `**Recommendation:**  \n${f.recommendation}\n\n`;
      if (f.evidence) {
        md += `**Evidence:**  \n\`\`\`\n${f.evidence}\n\`\`\`\n\n`;
      }
      md += `</details>\n\n`;
    }
  }

  // Medium/Low summary
  const mediumLow = [...(deploymentResult.findings || []), ...(codeResult.findings || [])]
    .filter(f => f.severity === 'MEDIUM' || f.severity === 'LOW');

  if (mediumLow.length > 0) {
    md += `### 📋 Additional Findings (${mediumLow.length})\n\n`;
    md += `<details>\n<summary>Click to expand</summary>\n\n`;
    for (const f of mediumLow) {
      const icon = config.severity.levels[f.severity]?.color || '❓';
      md += `- ${icon} **${f.severity}** — ${f.title} (\`${f.file || 'N/A'}\`)\n`;
    }
    md += `\n</details>\n\n`;
  }

  // Assessment
  md += `### 🚀 Deployment Assessment\n\n`;
  md += `${readiness.reason}\n\n`;
  md += `---\n`;
  md += `*🤖 AuthGuardian AI v${config.meta.version} — Automated IAM Governance Review*\n`;

  // Truncate if too long
  if (md.length > config.github.maxCommentSize) {
    md = md.substring(0, config.github.maxCommentSize - 200);
    md += `\n\n---\n⚠️ *Comment truncated due to size. See full reports in workflow artifacts.*\n`;
  }

  return md;
}

// ─────────────────────────────────────────────────────────────
// HELPER GENERATORS
// ─────────────────────────────────────────────────────────────

/**
 * Generates a markdown table of reviewed files.
 */
function generateFilesTable(files) {
  if (!files || files.length === 0) return '> No files to display.\n\n';

  let md = `| File | Resource Type | Change | Findings |\n`;
  md += `|------|--------------|--------|----------|\n`;

  for (const f of files) {
    const icon = f.resourceMeta?.icon || '📄';
    const type = f.resourceMeta?.label || f.resourceType || 'Unknown';
    const changeIcon = f.changeType === 'added' ? '🟢 Added' : f.changeType === 'modified' ? '🟡 Modified' : '🔴 Deleted';
    const findingCount = f.findings ? f.findings.length : 0;
    const findingLabel = findingCount > 0 ? `⚠️ ${findingCount}` : '✅ 0';
    md += `| ${icon} \`${f.filePath}\` | ${type} | ${changeIcon} | ${findingLabel} |\n`;
  }

  md += `\n`;
  return md;
}

/**
 * Generates detailed findings section with AI-style analysis.
 */
function generateFindingsSection(findings) {
  if (!findings || findings.length === 0) return '';

  // Group by severity
  const grouped = {};
  for (const f of findings) {
    if (!grouped[f.severity]) grouped[f.severity] = [];
    grouped[f.severity].push(f);
  }

  let md = '';

  for (const level of ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']) {
    const group = grouped[level];
    if (!group || group.length === 0) continue;

    const levelConfig = config.severity.levels[level];
    md += `### ${levelConfig.color} ${level} (${group.length})\n\n`;

    for (const f of group) {
      md += `#### ${levelConfig.color} ${f.title}\n\n`;
      md += `| Field | Details |\n`;
      md += `|-------|--------|\n`;
      md += `| **Severity** | ${level} |\n`;
      md += `| **Category** | ${f.category} |\n`;
      md += `| **File** | \`${f.file || 'N/A'}\` |\n`;
      md += `| **Resource** | ${f.resource || 'N/A'} |\n\n`;

      md += `**Description:**  \n${f.description}\n\n`;
      md += `**Impact:**  \n${f.impact}\n\n`;
      md += `**Recommendation:**  \n${f.recommendation}\n\n`;

      if (f.evidence) {
        md += `**Evidence:**\n\`\`\`\n${f.evidence}\n\`\`\`\n\n`;
      }

      md += `---\n\n`;
    }
  }

  return md;
}

/**
 * Generates recommendations section with governance insights.
 */
function generateRecommendationsSection(findings) {
  if (!findings || findings.length === 0) {
    return '> 🎉 No actionable recommendations. Configuration and code look secure.\n\n';
  }

  let md = '';

  // Deduplicate recommendations
  const seen = new Set();
  const uniqueRecs = [];
  for (const f of findings) {
    const key = `${f.id}-${f.recommendation}`;
    if (!seen.has(key)) {
      seen.add(key);
      uniqueRecs.push(f);
    }
  }

  // Sort by severity
  uniqueRecs.sort((a, b) => severityOrder(a.severity) - severityOrder(b.severity));

  let counter = 1;
  for (const f of uniqueRecs) {
    const icon = config.severity.levels[f.severity]?.color || '❓';
    md += `${counter}. ${icon} **${f.title}** — ${f.recommendation}\n`;
    counter++;
  }

  md += `\n`;
  return md;
}

/**
 * Generates Auth0 best practices checklist.
 */
function generateBestPracticesChecklist(codeResult) {
  let md = '';

  const checks = [
    { label: 'Auth0 Action Secrets used for credentials', pattern: /event\.secrets\./i },
    { label: 'Proper error handling (try/catch)', pattern: /try\s*\{/i },
    { label: 'Access denial patterns (api.access.deny)', pattern: /api\.access\.deny/i },
    { label: 'MFA enforcement (api.multifactor.enable)', pattern: /api\.multifactor\.enable/i },
    { label: 'Custom claims (api.idToken/accessToken.setCustomClaim)', pattern: /api\.(?:idToken|accessToken)\.setCustomClaim/i },
    { label: 'No eval() or dynamic code execution', pattern: /\beval\s*\(/i, negate: true },
    { label: 'No hardcoded secrets', pattern: /(?:password|secret|token)\s*[:=]\s*['"`][^'"`]{8,}/i, negate: true },
  ];

  for (const check of checks) {
    let found = false;
    for (const file of codeResult.reviewedFiles) {
      if (file.content && check.pattern.test(file.content)) {
        found = true;
        break;
      }
    }

    if (check.negate) {
      md += found ? `- ⚠️ ${check.label}\n` : `- ✅ ${check.label}\n`;
    } else {
      md += found ? `- ✅ ${check.label}\n` : `- ⬜ ${check.label} (not detected)\n`;
    }
  }

  md += `\n`;
  return md;
}

/**
 * Returns numeric order for severity (lower = more severe).
 */
function severityOrder(severity) {
  const order = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
  return order[severity] ?? 4;
}

module.exports = {
  generateDeploymentReport,
  generateCodeReviewReport,
  generateJobSummary,
  generatePrComment,
};
